spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001 

spring:
  profiles: dev
  application:
    name: shop-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.107.125.131:3306/cloudDB01
    username: root
    password: Zwt@8660966
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package:?com.atguigu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
info:
  app.name: shop-springcloud
  company.name: www.pagoda.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001 

spring:
  profiles: test
  application:
    name: shop-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.107.125.131:3306/cloudDB01
    username: root
    password: Zwt@8660966
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package:?com.atguigu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
info:
  app.name: shop-springcloud
  company.name: www.pagoda.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}